### ISSUE TITLE
The documentation site is broken

### ISSUE THREAD

**Issue by A9G-Data-Droid** [ZEISS-PiWeb/PiWeb-Import-Sdk#11]
**Affected Version(s)**
Currently public

**Describe the bug**
The link in the readme leads to this site: https://zeiss-piweb.github.io/PiWeb-Import-Sdk/
While that site looks good at first glance, all of the places where actual content would be expected contain only a link that says "Inprint" https://zeiss-piweb.github.io/PiWeb-Import-Sdk/docs/inprint.html

**To Reproduce**
1. Go to '(https://zeiss-piweb.github.io/PiWeb-Import-Sdk/)'
2. Click on 'Create your first plugin' (or any section)
3. There is no content

**Expected behavior**
I would expect content for each section.

**Screenshots**
![image](https://github.com/ZEISS-PiWeb/PiWeb-Import-Sdk/assets/26984068/c2a17a5c-eb4f-4701-9080-c7b3ae2c8a61)

**Additional context**
Is there another source for the documentation?

**Comment by daniel-schroeder-zeiss** [comment]
Hi,

unfortunately this skeleton page is the current extend of the documentation. We are still implementing the first version of this plugin system and will provide more documentation when important aspects of it are more stable than now.

**Comment by A9G-Data-Droid** [comment]
Ok, thanks. Maybe add some notice to users that the site is not finished because it looks like a regression.

**Comment by daniel-schroeder-zeiss** [comment]
Good point. I added a notice.
